### ISSUE TITLE
missing Building Area (sq ft)

### ISSUE THREAD

**Issue by kcamnairb** [bhelx/nola-assessor-data#1]
This is great. Thanks for sharing this. I noticed that the square footage of the building isn't available in your scraping of the 2020 data. Would you be able to add that to this data? Thanks.

**Comment by bhelx** [comment]
@kcamnairb Thanks for filing this issue. I'll take a look at it as soon as I get a free moment.

**Comment by bhelx** [comment]
@kcamnairb  are you using the postgres database or the CSVs? The sq/ft value is part of the `properties` table, not the `property_values` table. You'll need to join the two tables (or spreadsheets) if you want to include that information.

**Comment by bhelx** [comment]
I'm just now realizing that I did not have a `building_area_sq_ft` column and only a `land_area_sq_ft` column so I've pushed that change up. https://github.com/bhelx/nola-assessor-data/commit/1118e3066f667874cffb5c326309a65636c6f848

**Comment by kcamnairb** [comment]
Thanks
