### ISSUE TITLE
amazing! prop tax values back to 2015?

### ISSUE THREAD

**Issue by jonvoss** [bhelx/nola-assessor-data#2]
Hey just want to add my thanks for this, such an incredible public service you're doing here, with this state's insane tax policy. From what I can see, looks like you now have tax data from 2015-2020, is that correct? This can give us some great visibility into the impact the current state tax policy is having on New Orleans residents!

**Comment by bhelx** [comment]
Glad it's of help! Yes, the assessment data should go back to 2015. The site only shows 3 years but I've been accumulating for a few years now.
