### ISSUE TITLE
Tools to update database

### ISSUE THREAD

**Issue by rafmudaf** [bhelx/nola-assessor-data#5]
Hi @bhelx

Great work on this! Are you willing to share the tools for getting this data?
- Code to extract the assessments from each property site
- Script to get the endpoint for all properties
 
I'd like to update this database and set up GitHub Actions to update this periodically.

Thanks!

**Comment by bhelx** [comment]
I could send you the code. It's written in an older version of Elixir and is not really maintained.

This code here is based on the core ideas behind my Elixir code and is in python and maintained: https://github.com/codefornola/assessor-scraper
It's also supported by the code-for-nola community. You can talk to people about this in the Nola Devs slack on the #civic-hacking channel

One thing you might want to watch out for is that the tax assessor changed the layout of all their pages so any scraper you use might need to be updated to handle those changes. And you might need to find a new trick to enumerate all the resources if the search bug was fixed.

> I'd like to update this database and set up GitHub Actions to update this periodically.

I don't think you'll be able to do this in GitHub Actions. I was able to get it to run pretty quickly, but you have to balance scraping quickly and staying under their radar / not hurting their latency. You should run it in a VM somewhere ideally.

**Comment by rafmudaf** [comment]
Thanks for pointing out code-for-nola. I've looked through their projects and they generally seem stale since 2019, but that's a good starting point for me since I'm familiar with Python.

> And you might need to find a new trick to enumerate all the resources if the search bug was fixed.

This answers my second question. So it sounds like the method to get the list of all properties was a bug in the assessor's site. Maybe it's good enough in the short term to use the existing list of properties in the database and assume that very few new addresses are added. In any case, thanks for pointing this out.

And good point on the automation. It probably only should be updated once a year anyway, so easy enough to do it manually.

From here, I'll dig in to the @codefornola projects. Thanks a lot @bhelx!

**Comment by bhelx** [comment]
> This answers my second question. So it sounds like the method to get the list of all properties was a bug in the assessor's site. Maybe it's good enough in the short term to use the existing list of properties in the database and assume that very few new addresses are added. In any case, thanks for pointing this out.

not really a bug, more a hidden feature. but there was a hidden search interface where you could search for say `A` and enumerate through all the properties that start with A. then you do that for all alpha-nums all the way up to `9`. Then you have a list of about 180k urls to crawl (IIRC).

**Comment by bhelx** [comment]
Idea is outlined here: https://github.com/codefornola/assessor-scraper#get-all-the-parcel-ids
